REGEX_FULLNAME = "^[a-zA-Z0-9 ]*$"


# ALL SQL CONSTANT
SCHEMA = "dbo"
ACCOUNT_TABLE_NAME = "Account"
FOLLOWERS_TABLE_NAME = "Followers"
FOLLOWERS_VIEW = "FollowersView"
TEMP_ACCOUNT_TABLE_NAME = "NewAccount"
ACCESS_TOKEN_BLACKLIST_TABLE = "AccessTokenBlacklist"
NEW_SELL_TABLE_NAME = "NewSell"
NEW_SELL_VIEW_NAME = "CurrentNewSellView"
RESELL_TABLE_NAME = "Resale"
RESELL_VIEW_NAME = "CurrentResaleView"
TOKEN_TABLE_NAME = "Token"
SWARM_ENCRYPT_TABLE_NAME = "SwarmEncrypt"

DICTIONARY_FORMAT = {
    'png': 'png',
    'jpeg': 'jpeg',
    'jpg': 'jpeg'
}

ADDRESS_ALGO_OURSELF = 'HKDGSHRLJJLQP463PPTGIRQWMSPOIWR5CGAOCKOHOEH3WEU44SEYIDHPR4'
PROFILE_PICTURES_CONTAINER = "profile"
